# Generated by Django 4.1.6 on 2024-01-14 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plataforma", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aacc_para_avaliacao",
            name="id_avaliador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Login",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
